apiVersion: v1
kind: Service
metadata:
  name: cloud-assignment-service
spec:
  type: LoadBalancer
  selector:
    app: cloud-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80